---

- name: install php package
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
  - php

- name: check if httpd is running
  service:
    name: httpd 
    state: started
 
- name: Open port 80 for http access
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: Restart the firewalld service to load in the firewall changes
  service: 
    name: firewalld 
    state: restarted
