---

- name: install SQL packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - mysql-server
    - php-mysql

- name: Start Mysql
  service: name=mysql state=started enabled=yes

- name: Creer Application Database
  mysql_db: name={{ dbname }} state=present

- name: Creer Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
